"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription,
} from "@/components/ui/dialog";
import { Sparkles, PenTool, Wand2, Loader2, ArrowRight } from "lucide-react";
import { toast } from "sonner";
import { useStudio } from "@/lib/store";
import { useAuth } from "@/lib/auth-store";
import type { WorkflowNode, WorkflowEdge, Agent } from "@/lib/types";

const uid = () => Math.random().toString(36).slice(2, 10);

export function AIBuilderModal({
  open, onOpenChange,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
}) {
  const [mode, setMode] = useState<"choose" | "scratch" | "describe">("choose");
  const [description, setDescription] = useState("");
  const [name, setName] = useState("");
  const [generating, setGenerating] = useState(false);

  const { setView, setGraph, setActiveAgent, upsertAgent } = useStudio();
  const { user } = useAuth();

  function reset() {
    setMode("choose");
    setDescription("");
    setName("");
    setGenerating(false);
  }

  function createScratch() {
    // Create a blank agent with default nodes
    const nodes: WorkflowNode[] = [
      { id: `trigger-${uid()}`, type: "agent", position: { x: 80, y: 240 }, data: { label: "Input", kind: "trigger", content: "User message" } },
      { id: `model-${uid()}`, type: "agent", position: { x: 400, y: 240 }, data: { label: "GLM Model", kind: "model", provider: "glm-4.5-air", systemPrompt: "You are a helpful AI agent. Respond clearly and concisely." } },
      { id: `output-${uid()}`, type: "agent", position: { x: 720, y: 240 }, data: { label: "Response", kind: "output" } },
    ];
    const edges: WorkflowEdge[] = [
      { id: `e-${uid()}`, source: nodes[0].id, target: nodes[1].id, animated: true },
      { id: `e-${uid()}`, source: nodes[1].id, target: nodes[2].id, animated: true },
    ];
    finishCreate(name || "Untitled Agent", "", "sparkles", nodes, edges);
  }

  async function generateFromDescription() {
    if (!description.trim()) return;
    setGenerating(true);
    try {
      const res = await fetch("/api/agents/generate", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ description }),
      });
      if (!res.ok) throw new Error();
      const data = await res.json() as {
        name: string;
        description: string;
        icon: string;
        category: string;
        nodes: WorkflowNode[];
        edges: WorkflowEdge[];
        _fallback?: boolean;
      };
      if (data._fallback) {
        toast.success("Agent created (using a template — AI generation had an issue)");
      } else {
        toast.success("Agent generated by AI!");
      }
      finishCreate(data.name, data.description, data.icon, data.nodes, data.edges);
    } catch {
      toast.error("Could not generate agent — try again or create from scratch");
    } finally {
      setGenerating(false);
    }
  }

  async function finishCreate(name: string, description: string, icon: string, nodes: WorkflowNode[], edges: WorkflowEdge[]) {
    // Persist to DB
    try {
      const res = await fetch("/api/agents", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ name, description, icon, nodes, edges, firebaseUid: user?.firebaseUid }),
      });
      if (res.ok) {
        const agent = (await res.json()) as Agent;
        upsertAgent(agent);
        setActiveAgent(agent);
      }
    } catch {
      // non-fatal
    }
    setGraph(nodes, edges);
    onOpenChange(false);
    reset();
    setView("studio");
  }

  return (
    <Dialog open={open} onOpenChange={(v) => { onOpenChange(v); if (!v) reset(); }}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" />
            {mode === "choose" && "Create a New Agent"}
            {mode === "scratch" && "Create from Scratch"}
            {mode === "describe" && "Describe an Idea"}
          </DialogTitle>
          <DialogDescription>
            {mode === "choose" && "Choose how you'd like to build your agent."}
            {mode === "scratch" && "Start with a blank canvas and a basic Input → Model → Output workflow."}
            {mode === "describe" && "Describe what your agent should do — AI will design the full workflow for you."}
          </DialogDescription>
        </DialogHeader>

        {mode === "choose" && (
          <div className="grid gap-3 pt-2">
            <button
              onClick={() => setMode("describe")}
              className="group flex items-start gap-3 rounded-xl border border-border p-4 text-left transition-all hover:border-primary/50 hover:bg-accent"
            >
              <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-primary/15 text-primary">
                <Wand2 className="h-5 w-5" />
              </div>
              <div className="flex-1">
                <div className="flex items-center gap-1.5 font-medium">
                  Describe an Idea
                  <span className="rounded-full bg-primary/15 px-1.5 py-0.5 text-[9px] font-semibold uppercase text-primary">AI</span>
                </div>
                <p className="mt-0.5 text-xs text-muted-foreground">
                  Tell the AI what you want — it designs the nodes, prompts, and connections automatically.
                </p>
              </div>
              <ArrowRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-1" />
            </button>

            <button
              onClick={() => setMode("scratch")}
              className="group flex items-start gap-3 rounded-xl border border-border p-4 text-left transition-all hover:border-primary/50 hover:bg-accent"
            >
              <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-muted text-muted-foreground">
                <PenTool className="h-5 w-5" />
              </div>
              <div className="flex-1">
                <div className="font-medium">Create from Scratch</div>
                <p className="mt-0.5 text-xs text-muted-foreground">
                  Start with a blank canvas. Drag nodes, connect them, and build manually.
                </p>
              </div>
              <ArrowRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-1" />
            </button>
          </div>
        )}

        {mode === "scratch" && (
          <div className="space-y-3 pt-2">
            <div className="space-y-1.5">
              <label className="text-xs font-medium">Agent name</label>
              <Input
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="My New Agent"
                className="h-9"
                autoFocus
              />
            </div>
            <div className="flex gap-2 pt-2">
              <Button variant="outline" onClick={() => setMode("choose")}>Back</Button>
              <Button onClick={createScratch} className="flex-1 gap-1.5">
                <PenTool className="h-4 w-4" /> Create Agent
              </Button>
            </div>
          </div>
        )}

        {mode === "describe" && (
          <div className="space-y-3 pt-2">
            <div className="space-y-1.5">
              <label className="text-xs font-medium">What should your agent do?</label>
              <Textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="e.g. A customer support agent that searches our docs, classifies the ticket urgency, and drafts a helpful reply with next steps."
                rows={4}
                autoFocus
                onKeyDown={(e) => {
                  if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
                    e.preventDefault();
                    generateFromDescription();
                  }
                }}
              />
              <p className="text-[11px] text-muted-foreground">Press Cmd/Ctrl+Enter to generate</p>
            </div>

            {/* Example prompts */}
            <div className="flex flex-wrap gap-1.5">
              {EXAMPLES.map((ex) => (
                <button
                  key={ex}
                  onClick={() => setDescription(ex)}
                  className="rounded-full border border-border bg-background px-2.5 py-1 text-[11px] text-muted-foreground transition-colors hover:border-primary/50 hover:text-foreground"
                >
                  {ex.slice(0, 40)}…
                </button>
              ))}
            </div>

            <div className="flex gap-2 pt-2">
              <Button variant="outline" onClick={() => setMode("choose")}>Back</Button>
              <Button
                onClick={generateFromDescription}
                disabled={!description.trim() || generating}
                className="flex-1 gap-1.5"
              >
                {generating ? (
                  <><Loader2 className="h-4 w-4 animate-spin" /> Generating…</>
                ) : (
                  <><Wand2 className="h-4 w-4" /> Generate Agent</>
                )}
              </Button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

const EXAMPLES = [
  "A research assistant that searches the web and writes a structured brief",
  "An AI code reviewer that finds bugs and rates severity",
  "A social media content generator that creates posts and images",
  "A support bot that routes tickets by keyword to different experts",
];
